version: "3"
services:
  traversability:
    image: traversability:1.0
    volumes:
      #full dev
      - /dev:/dev:rw
      #full media
      - /media:/media:rw
      #Time
      - /etc/timezone:/etc/timezone:rw
      - /etc/localtime:/etc/localtime:rw
      #code
      - ./:/root/
    privileged: true
    network_mode: host
    ipc: host
    stdin_open: true
    tty: true
    environment:
      - DISPLAY
    entrypoint: /bin/bash