/**:
  traversability_node:
    ros__parameters:
      additions_topic_name: "traversability_keyframe_additions"
      updates_topic_name: "traversability_keyframe_updates"
      pointcloud_topic_name: "lidar/points"
      use_lidar_pointcloud: false
      publish_traversability_grid: true
      is_kf_optimization_enabled: false
      slam_frame: base_footprint
      robot_base_frame: base_footprint
      lidar_frame: lidar_link

  local_traversability_node:
    ros__parameters:
      additions_topic_name: "traversability_keyframe_additions"
      updates_topic_name: "traversability_keyframe_updates"
      slam_frame: base_footprint
      robot_base_frame: base_footprint
      lidar_frame: lidar_link
      map_frame: map

  traversability_threshold_node:
    ros__parameters:
      lethal_obstacle_threshold: 55 # between 0 to 100
  
  slam_keyframe_pcl_simulator:
    ros__parameters:
      pose_type: "odom"
      odom_topic: "ground_truth_pose"
      pcl_topic: "lidar/points"
      keyframe_publish_rate_hz: 2.5 # Hz.
      per_keyframe_translation_error_m: 0.05
      per_keyframe_yaw_error_deg: 0.04