/**:
  traversability_node:
    ros__parameters:
      use_sim_time: True
      additions_topic_name: "traversability_keyframe_additions"
      updates_topic_name: "traversability_keyframe_updates"
      pointcloud_topic_name: "lidar/points"
      use_lidar_pointcloud: false
      publish_traversability_grid: true
      is_kf_optimization_enabled: false

  local_traversability_node:
    ros__parameters:
      use_sim_time: True
      pointcloud_topic_name: "lidar/points"
      expected_frequency: 4.0 # Hz.

  traversability_threshold_node:
    ros__parameters:
      use_sim_time: True
      lethal_obstacle_threshold: 55 # between 0 to 100