/**:
  traversability_node:
    ros__parameters:
      additions_topic_name: "traversability_keyframe_additions"
      updates_topic_name: "traversability_keyframe_updates"
      pointcloud_topic_name: "lidar/points"
      use_lidar_pointcloud: false
      publish_traversability_grid: true
      is_kf_optimization_enabled: false
      slam_frame: base_footprint
      robot_base_frame: base_footprint
      lidar_frame: lidar_link

  local_traversability_node:
    ros__parameters:
      pointcloud_topic_name: "lidar/points"
      expected_frequency: 4.0 # Hz.
      slam_frame: base_footprint
      robot_base_frame: base_footprint
      lidar_frame: lidar_link

  traversability_threshold_node:
    ros__parameters:
      lethal_obstacle_threshold: 80 # between 0 to 100
  
  slam_keyframe_pcl_simulator:
    ros__parameters:
      odom_topic: "ground_truth_pose"
      pcl_topic: "lidar/points"
      keyframe_publish_rate_hz: 2.5 # Hz.