/**:
  traversability_node:
    ros__parameters:
      additions_topic_name: "traversability_keyframe_additions"
      updates_topic_name: "traversability_keyframe_updates"
      pointcloud_topic_name: "lidar/points"
      use_lidar_pointcloud: false
      publish_traversability_grid: true
      is_kf_optimization_enabled: false
      slam_frame: zed_camera_center
      robot_base_frame: zed_camera_center
      lidar_frame: zed_left_camera_frame

  local_traversability_node:
    ros__parameters:
      additions_topic_name: "traversability_keyframe_additions"
      updates_topic_name: "traversability_keyframe_updates"
      slam_frame: zed_camera_center
      robot_base_frame: zed_camera_center
      lidar_frame: zed_left_camera_frame
      map_frame: map

  traversability_threshold_node:
    ros__parameters:
      lethal_obstacle_threshold: 55 # between 0 to 100
  
  slam_keyframe_pcl_simulator:
    ros__parameters:
      pose_type: "pose_stamped"
      odom_topic: "/zed/zed_node/pose"
      pcl_topic: "/zed/zed_node/point_cloud/cloud_registered"
      keyframe_publish_rate_hz: 2.5 # Hz.