/**:
  traversability_node:
    ros__parameters:
      additions_topic_name: "traversability_keyframe_additions"
      updates_topic_name: "traversability_keyframe_updates"
      pointcloud_topic_name: "lidar/points"
      use_lidar_pointcloud: true
      publish_traversability_grid: true
      is_kf_optimization_enabled: true

  local_traversability_node:
    ros__parameters:
      pointcloud_topic_name: "lidar/points"
      expected_frequency: 4.0 # Hz.
      slam_frame: base_footprint

  traversability_threshold_node:
    ros__parameters:
      lethal_obstacle_threshold: 55 # between 0 to 100