name: Humble

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: cp docker/humble/* . && sudo docker build -t traversability_humble:1.0 .
    - name: Cleanup
      run: sudo docker rmi --force traversability_humble:1.0 && rm -rf Dockerfile docker-compose.yaml
