name: Jazzy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: cd docker/jazzy && sudo docker build -t traversability_jazzy:1.0 .
    - name: Cleanup
      run: sudo docker rmi traversability_jazzy:1.0