name: Humble
on:
  push:
    branches:
    - 'master'
  pull_request:
    branches:
    - '*'
jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        config:
          - {rosdistro: 'humble', container: 'ros:humble'}
    container: ${{ matrix.config.container }}
    steps:
    - uses: actions/checkout@v4
      with:
        path: src/traversability_mapping
    - name: Install Dependencies with Rosdep
      run: |
        apt update
        rosdep update
        source /opt/ros/${{matrix.config.rosdistro}}/setup.bash
        rosdep install --from-paths src --ignore-src -y --skip-keys sophus
      shell: bash
    - name: Colcon Build (Release)
      run: |
        source /opt/ros/${{matrix.config.rosdistro}}/setup.bash
        colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release
      shell: bash